# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
"""Generated DTO layer: the wire-format types shared with the .NET reference client."""

from .bridgemate_settings_dto import BridgemateSettingsDTO
from .continue_dto import ContinueDTO
from .handrecord_dto import HandrecordDTO
from .init_dto import InitDTO
from .participation_dto import ParticipationDTO
from .player_data_dto import PlayerDataDTO
from .result_dto import ResultDTO
from .round_dto import RoundDTO
from .scoring_group_dto import ScoringGroupDTO
from .scoring_program_request import ScoringProgramRequest
from .scoring_program_response import ScoringProgramResponse
from .section_dto import SectionDTO
from .section_update_dto import SectionUpdateDTO
from .session_dto import SessionDTO
from .table_dto import TableDTO
from .td_call_dto import TdCallDTO
from .bridgemate2_settings_dto import Bridgemate2SettingsDTO
from .bridgemate3_settings_dto import Bridgemate3SettingsDTO
from .bm2_result_entry_method import BM2ResultEntryMethod
from .bm3_player_view_option import BM3PlayerViewOption
from .bm3_starting_positions_option import BM3StartingPositionsOption
from .bm2_contract_representation_option import Bm2ContractRepresentationOption
from .bm2_enter_handrecord_when_option import Bm2EnterHandrecordWhenOption
from .bm2_name_source import Bm2NameSource
from .bm2_number_validation_option import Bm2NumberValidationOption
from .bm2_pair_number_entry_option import Bm2PairNumberEntryOption
from .bm2_point_score_perspective_option import Bm2PointScorePerspectiveOption
from .bm2_results_overview_option import Bm2ResultsOverviewOption
from .bm2_show_player_names_option import Bm2ShowPlayerNamesOption
from .bm2_show_ranking_option import Bm2ShowRankingOption
from .bm2_summary_point_option import Bm2SummaryPointOption
from .bm3_confirm_np_option import Bm3ConfirmNPOption
from .bm3_connection_mode_option import Bm3ConnectionModeOption
from .bm3_enter_handrecord_option import Bm3EnterHandrecordOption
from .bm3_language_option import Bm3LanguageOption
from .bm3_lead_card_entry_option import Bm3LeadCardEntryOption
from .bm3_next_round_seating_option import Bm3NextRoundSeatingOption
from .bm3_player_number_mandatory_option import Bm3PlayerNumberMandatoryOption
from .bm3_player_registration_option import Bm3PlayerRegistrationOption
from .bm3_player_registration_option_during_play import Bm3PlayerRegistrationOptionDuringPlay
from .bm3_ranking_display_option import Bm3RankingDisplayOption
from .bm3_result_entry_method import Bm3ResultEntryMethod
from .bm3_result_reentry_option import Bm3ResultReentryOption
from .bm3_score_column_option import Bm3ScoreColumnOption
from .bm3_score_recap_option import Bm3ScoreRecapOption
from .bm3_session_summary_option import Bm3SessionSummaryOption
from .bm3_td_call_option import Bm3TdCallOption
from .bm3_view_handrecord_option import Bm3ViewHandrecordOption
from .bm3_view_percentages_option import Bm3ViewPercentagesOption
from .bm3_view_results_option import Bm3ViewResultsOption
from .data_connector_response_data import DataConnectorResponseData
from .error_type import ErrorType
from .scoring_program_data_connector_commands import ScoringProgramDataConnectorCommands
from .table_direction import TableDirection

__all__ = [
    "BridgemateSettingsDTO",
    "ContinueDTO",
    "HandrecordDTO",
    "InitDTO",
    "ParticipationDTO",
    "PlayerDataDTO",
    "ResultDTO",
    "RoundDTO",
    "ScoringGroupDTO",
    "ScoringProgramRequest",
    "ScoringProgramResponse",
    "SectionDTO",
    "SectionUpdateDTO",
    "SessionDTO",
    "TableDTO",
    "TdCallDTO",
    "Bridgemate2SettingsDTO",
    "Bridgemate3SettingsDTO",
    "BM2ResultEntryMethod",
    "BM3PlayerViewOption",
    "BM3StartingPositionsOption",
    "Bm2ContractRepresentationOption",
    "Bm2EnterHandrecordWhenOption",
    "Bm2NameSource",
    "Bm2NumberValidationOption",
    "Bm2PairNumberEntryOption",
    "Bm2PointScorePerspectiveOption",
    "Bm2ResultsOverviewOption",
    "Bm2ShowPlayerNamesOption",
    "Bm2ShowRankingOption",
    "Bm2SummaryPointOption",
    "Bm3ConfirmNPOption",
    "Bm3ConnectionModeOption",
    "Bm3EnterHandrecordOption",
    "Bm3LanguageOption",
    "Bm3LeadCardEntryOption",
    "Bm3NextRoundSeatingOption",
    "Bm3PlayerNumberMandatoryOption",
    "Bm3PlayerRegistrationOption",
    "Bm3PlayerRegistrationOptionDuringPlay",
    "Bm3RankingDisplayOption",
    "Bm3ResultEntryMethod",
    "Bm3ResultReentryOption",
    "Bm3ScoreColumnOption",
    "Bm3ScoreRecapOption",
    "Bm3SessionSummaryOption",
    "Bm3TdCallOption",
    "Bm3ViewHandrecordOption",
    "Bm3ViewPercentagesOption",
    "Bm3ViewResultsOption",
    "DataConnectorResponseData",
    "ErrorType",
    "ScoringProgramDataConnectorCommands",
    "TableDirection",
]
