# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
"""Internal helper shared by the generated DTO modules."""


def enum_from_wire(enum_cls, value, default=None):
    """Maps a wire value to the enum.

    None (absent or JSON null) falls back to the default. Unknown values from a newer
    Data Connector either map through the enum's _missing_ hook (enums with a zero
    case) or fall back to the default here, instead of failing the whole response.
    """
    if value is None:
        return default
    try:
        return enum_cls(value)
    except ValueError:
        return default
