# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm2PointScorePerspectiveOption(IntEnum):
    """Show the pointscore sign (plus or minus) from the perspective of declarer or North-South."""

    # Show the pointscore sign (plus or minus) from the perspective of North-South.
    FromNorthSouth = 0
    # Show the pointscore sign (plus or minus) from the perspective of declarer.
    FromDeclarer = 1

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.FromNorthSouth
