# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm2ShowPlayerNamesOption(IntEnum):
    """Specifies whether and when to show the names of the competing pairs."""

    # Do not show.
    DoNotShow = 0
    # Show in all rounds.
    ShowInAllRounds = 1
    # Show in first round only.
    ShowInFirstRoundOnly = 2

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.DoNotShow
