# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm2ShowRankingOption(IntEnum):
    """Specifies whether and when to show the ranking."""

    # Do not show.
    DoNotShow = 0
    # Show the ranking after each round.
    ShowAllRounds = 1
    # Show the ranking after the last round only.
    ShowAfterLastRound = 2

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.DoNotShow
