# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm2NumberValidationOption(IntEnum):
    """Specifies for which organization an entered playernumber should be validated."""

    # No validation.
    NoValidation = 0
    # Validate for the ACBL (USA).
    ACBL = 1
    # Validate for the FFB (France).
    FFB = 2
    # Validate for the ABF (Australia).
    ABF = 3
    # Validate for the JCBL (Japanese).
    JCBL = 4

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.NoValidation
