# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm2ContractRepresentationOption(IntEnum):
    """How to represent the contract denomination"""

    # Use the symbols for clubs, diamonds, hearts and spades
    UseSymbols = 0
    # Use letters for the denominations
    UseLetter = 1

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.UseSymbols
