# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm2EnterHandrecordWhenOption(IntEnum):
    """Specifies whether and when the players can enter the handrecord for a board."""

    # The handrecord can be entered at the end of each round.
    AtEndOfRound = 0
    # The handrecord can be entered after the play of each board.
    AtEndOfBoard = 1
    # The handrecord cannot be entered.
    DoNotEnter = 2

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.AtEndOfRound
