# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm2NameSource(IntEnum):
    """Specifies which source data should be consulted to look up player names for player numbers."""

    # The PlayerNames table of the .bws scoring file.
    PlayerNamesTable = 0
    # A separate MS-Access table.
    BMPlayerDB = 1
    # No External source.
    NoExternalSource = 2
    # First check the PlayerNames table then the external MS-Access file.
    PlayerNamesTableThenBMPlayerDB = 3

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.PlayerNamesTable
