# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm2PairNumberEntryOption(IntEnum):
    """Specifies if the pairnumber should be part of entering the contract."""

    # The pairnumber cannot be entered.
    NoEntry = 0
    # The pairnumber entry is optional.
    Optional = 1
    # The pairnumber entry is required.
    Required = 2

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.NoEntry
