# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm2SummaryPointOption(IntEnum):
    """Specifies whether and how to show the summary points after the last round."""

    # Show the scores as matchpoints.
    Matchpoints = 0
    # Show the scores a percentages.
    Percentage = 1
    # Do not show.
    NoSummary = -1

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.Matchpoints
