# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm3EnterHandrecordOption(IntEnum):
    """Specifies whether and when handrecords can be entered by the players."""

    # Handrecords cannot be entered by the players.
    Disabled = 0
    # Handrecords can be entered after play of the board.
    AtEndOfBoard = 1
    # Handrecords can be entered at the end of the round.
    AtEndOfRound = 2

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.Disabled
