# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm3RankingDisplayOption(IntEnum):
    """Specifies whether and when the ranking can be consulted."""

    # The ranking cannot be consulted.
    Disabled = 0
    # The ranking can be consulted at the end of each round.
    EndOfEachRound = 1
    # The ranking can be consulted at the end of the last round.
    EndOfSession = 2
    # The ranking can be consulted at any moment.
    Always = 3

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.Disabled
