# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm3ScoreRecapOption(IntEnum):
    """Specifies if all the results obtained in the round can be consulted."""

    # The results obtained in the round cannot be consulted.
    Disabled = 0
    # The results obtained in the round can be consulted at the end of the round only.
    EnabledAtEndOfRoundOnly = 1
    # The results obtained in the round can be consulted at any time.
    Always = 2

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.Disabled
