# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class BM3StartingPositionsOption(IntEnum):
    """Specifies whether starting positions should be confirmed by players at start of the session"""

    # Players cannot / may no confirm starting positions (NE/SW) at start of the session
    Disabled = 0
    # Players must confirm starting positions (NE/SW) at start of the session
    Enabled = 1

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.Disabled
