# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm3ConfirmNPOption(IntEnum):
    """Specifies if a not played entry must be confirmed by the TD"""

    # TD must not confirm Not Played
    Disabled = 0
    # TD must confirm Not Played
    Enabled = 1

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.Disabled
