# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm3ViewHandrecordOption(IntEnum):
    """Specifies whether players can consult the handrecord for a board they just played."""

    # Handrecords cannot be consulted.
    Disabled = 0
    # Handrecords can be consulted after play of the board.
    Enabled = 1

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.Disabled
