# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm3SessionSummaryOption(IntEnum):
    """Specifies whether session summaries are enabled or disabled."""

    # Indicates that the feature or functionality is disabled.
    Disabled = 0
    # Indicates that the feature or functionality is enabled.
    Enabled = 1

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.Disabled
