# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm3PlayerRegistrationOptionDuringPlay(IntEnum):
    """Specifies whether player can make themselves known once the round has started."""

    # Players can make themselved known at the start of the round, before any result has been
    # entered.
    Disabled = 0
    # Players can make themselves known during any stage of the round.
    Enabled = 1

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.Disabled
