# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm3ConnectionModeOption(IntEnum):
    """Specifies whether the Bridgemates for the section will work in online mode (continuous
    communication with the Bridgemate 3 server) or if they work in offline mode (communication
    only at the start and the end of the session).
    """

    # The Bridgemates for the section will work in online mode (continuous communication with the
    # Bridgemate 3 server).
    Online = 0
    # The Bridgemates for the section will work in offline mode (communication will be initiated at
    # the end of the session or can be initiated manually).
    Offline = 1

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.Online
