# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm3ScoreColumnOption(IntEnum):
    """Specifies if there should be one column (for NS only) or two (for both NS and EW)."""

    # Show one column, for NS.
    NorthSouthOnly = 0
    # Shpw two columns, for NS and EW.
    NorthSouthAndEastWest = 1

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.NorthSouthOnly
