# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm3LanguageOption(IntEnum):
    """Specifies which language should be used on the Bridgemate."""

    # English
    English = 0
    # Dutch
    Dutch = 1
    # French
    French = 2
    # German
    German = 3
    # Italian
    Italian = 4
    # Danish
    Danish = 5
    # Spanish
    Spanish = 6
    # Norwegian
    Norwegian = 7
    # Polish
    Polish = 8
    # Swedish
    Swedish = 9
    # Turkish
    Turkish = 10

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.English
