# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm3ViewPercentagesOption(IntEnum):
    """Specifies wheter to include the own score for a board in the result overview."""

    # Do not include the own score for a board in the result overview.
    Disabled = 0
    # Include the own score for a board in the result overview.
    Enabled = 1

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.Disabled
