# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm3TdCallOption(IntEnum):
    """Specifies of the players can call the TD using the Bridgemate."""

    # The players cannot call the TD using the Bridgemate.
    Disabled = 0
    # The players can call the TD using the Bridgemate.
    Enabled = 1

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.Disabled
