# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class BM3PlayerViewOption(IntEnum):
    """Specifies how the wind rose player view is displayed"""

    # players are displayed with north at the top
    NorthOnTop = 0
    # players are displayed with north at the bottom
    NorthOnTheBottom = 1

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.NorthOnTop
