# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm3NextRoundSeatingOption(IntEnum):
    """Specifies whether the tables for the next round should be displayed after the current round
    ends.
    """

    # Do not display the tables for the next round.
    Disabled = 0
    # Display the tables for the next round after the current round ends.
    Enabled = 1

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.Disabled
