# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm3LeadCardEntryOption(IntEnum):
    """Specifies whether the lead card must be entered and how this will be validated."""

    # No lead card entry.
    Disabled = 0
    # The lead card must be entered. It will not be validated against the handrecord.
    EnabledNoValidation = 1
    # The lead card must be entered. It will be validated against the handrecord and it must be
    # changed if validation fails.
    EnabledWithValidationMustComply = 2
    # The lead card must be entered. It will be validated against the handrecord and a warning is
    # issued if validation fails.
    EnabledWithValidationAllowNonCompliance = 3

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.Disabled
