# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class Bm3PlayerRegistrationOption(IntEnum):
    """Specifies wheter and when players can make themselves known."""

    # Player cannot make themselves known by entering their detaiils.
    Disabled = 0
    # Player can make themselves known by entering their details in the first round only.
    FirstRoundOnly = 1
    # Player can make themselves known by entering their details in all rounds.
    AllRounds = 2

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.Disabled
