# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from dataclasses import dataclass

from ._support import enum_from_wire
from .bm2_contract_representation_option import Bm2ContractRepresentationOption
from .bm2_enter_handrecord_when_option import Bm2EnterHandrecordWhenOption
from .bm2_name_source import Bm2NameSource
from .bm2_number_validation_option import Bm2NumberValidationOption
from .bm2_pair_number_entry_option import Bm2PairNumberEntryOption
from .bm2_point_score_perspective_option import Bm2PointScorePerspectiveOption
from .bm2_result_entry_method import BM2ResultEntryMethod
from .bm2_results_overview_option import Bm2ResultsOverviewOption
from .bm2_show_player_names_option import Bm2ShowPlayerNamesOption
from .bm2_show_ranking_option import Bm2ShowRankingOption
from .bm2_summary_point_option import Bm2SummaryPointOption
from .bridgemate_settings_dto import BridgemateSettingsDTO


@dataclass
class Bridgemate2SettingsDTO(BridgemateSettingsDTO):
    """Contains all settings for the Bridgemate 2 for a section. Mind that all values must be
    supplied.
    """

    # Show results obtained on other rounds and on other tables.
    show_results: bool = False

    # Include the own result in the results overview.
    show_own_result: bool = False

    # Ask after showing the results if the overview should be repeated.
    repeat_results: bool = False

    # Show percentage rather than matchpoints.
    show_percentage: bool = False

    # Currently not supported. Use the ScoringGroupDTO to group sections.
    group_sections: bool = False

    # Show the point score of a result from the declarer's perspective or from that of North-South.
    score_points: Bm2PointScorePerspectiveOption = Bm2PointScorePerspectiveOption.FromNorthSouth

    # Defines the way resulting tricks are enterd after the board has been played.
    enter_results_method: BM2ResultEntryMethod = BM2ResultEntryMethod.UpDownTricks

    # Determines if the pairnumbers are shown at the top of the Bridgemate.
    show_pair_numbers: bool = False

    # Currently not supported.
    intermediate_results: bool = False

    # The time in seconds before the Bridgemate will power off.
    autopoweroff_time: int = 0

    # The time in seconds that the message that the opponents must confirm the entered result is
    # shown.
    verification_time: int = 0

    # Show the denomination of the contract as letters or as suit symbols.
    show_contract: Bm2ContractRepresentationOption = Bm2ContractRepresentationOption.UseSymbols

    # Defines if the leadcard should be entered.
    lead_card: bool = False

    # If ShowResults is "True" determines the maximum number of results that will be shown.
    maximum_results: int = 0

    # Defines if the players can make themselves know by entering their player number on the
    # Bridgemate.
    member_numbers: bool = False

    # If "True" all players must have been identified by their player number.
    member_numbers_no_blank_entry: bool = False

    # Defines if the Bridgemate should check the order of play.
    board_order_verification: bool = False

    # Currently not supported.
    hand_record_validation: bool = False

    # Defines if BCS should automatically shut down when all results are in.
    auto_shut_down_bpc: bool = False

    # The pincode that the TD must enter before accessing the TD menu on the Bridgemate. Must be
    # four digits.
    bm2_pi_ncode: str | None = None

    # Defines if the TD must confirm No Play on the Bridgemate.
    bm2_confirm_np: bool = False

    # Defines if the Bridgemate should show how many boards in the round are left to play.
    bm2_remaining_boards: bool = False

    # Defines if the Bridgemate should show the seatings for the next round.
    bm2_next_seatings: bool = False

    # Defines if the Bridgemate can show the scores obtained during the round when a player presses
    # the appropriate button on the Bridgemate.
    bm2_score_recap: bool = False

    # Defines if the Bridgemate should show the score recap wihtout promptimg after the last board
    # of the round has been played..
    bm2_auto_show_score_recap: bool = False

    # Defines if the players can correct scores themselves. If not the TD must be called to the
    # table to do this.
    bm2_score_correction: bool = False

    # Defines if the Brigemate should enter the board number automatically..
    bm2_auto_board_number: bool = False

    # If BM2AutoBoardNumber is "True" defines if the boardnumber of the first board should be
    # entered manually. The subsequent boards will be filled in automatically.
    bm2_first_board_manually: bool = False

    # Determines if the entry of the leadcard should be checked against the handrecord.
    bm2_validate_lead_card: bool = False

    # Determines how the results overview will be formatted on the display.
    bm2_results_overview: Bm2ResultsOverviewOption = Bm2ResultsOverviewOption.FrequencyList6lines1column

    # Determines if the Bridgemate shows the names of the players and if so at the start of each
    # round or in the first round only.
    bm2_show_player_names: Bm2ShowPlayerNamesOption = Bm2ShowPlayerNamesOption.DoNotShow

    # Determines if the Bridgemate should show the ranking and if so after play of the last board of
    # a round or after play of the last board of the session..
    bm2_ranking: Bm2ShowRankingOption = Bm2ShowRankingOption.DoNotShow

    # Enable/disable the summary after end of session. (Enabled requires BM2Ranking=1 or 2
    bm2_game_summary: bool = False

    # Defines if matchpoints or the percentage should be shown in the game summary.
    bm2_summary_points: Bm2SummaryPointOption = Bm2SummaryPointOption.Matchpoints

    # Defines if the players can or must enter the pair number when entering the declaring side for
    # a contract. Enforcing this helps in detecting switched seatings.
    bm2_pair_number_entry: Bm2PairNumberEntryOption = Bm2PairNumberEntryOption.NoEntry

    # Determines if the "Reset" key is available to the players, rather than to the TD only.
    bm2_reset_function_key: bool = False

    # Currently not supported.
    bm2_record_bidding: bool = False

    # Currently not supported.
    bm2_record_play: bool = False

    # Currently not supported.
    bm2_validate_recording: bool = False

    # Currently not suppoorted.
    bm2_show_hands: bool = False

    # Currently not supported
    number_validation: Bm2NumberValidationOption = Bm2NumberValidationOption.NoValidation

    # Defines if the players must enter their player number each round.
    bm2_number_entry_each_round: bool = False

    # Currently not supported.
    bm2_number_entry_preload_values: bool = False

    # Currently not supported.
    bm2_name_source: Bm2NameSource = Bm2NameSource.PlayerNamesTable

    # Determines if the players can see the handrecord of the board they just played.
    bm2_view_hand_record: bool = False

    # Determines if the players can enter the handrecord for boards they played if not present.
    bm2_enter_hand_record: bool = False

    # If BM2EnterHandRecord is "True" determines if the players can enter the handrecord after play
    # of the board or after playing all boards for the round.
    bm2_enter_hand_record_when: Bm2EnterHandrecordWhenOption = Bm2EnterHandrecordWhenOption.AtEndOfRound

    # Currently not supported.
    bm2_text_based_number: bool = False

    # Defines if the "Call TD" button is visible on the Bridgemate.
    bm2_td_call: bool = False

    def to_dict(self) -> dict:
        """The JSON-ready dict with the PascalCase wire names, in wire order."""
        return {
            "SessionGuid": self.session_guid,
            "SectionLetters": self.section_letters,
            "ValidationMessages": self.validation_messages,
            "ShowResults": self.show_results,
            "ShowOwnResult": self.show_own_result,
            "RepeatResults": self.repeat_results,
            "ShowPercentage": self.show_percentage,
            "GroupSections": self.group_sections,
            "ScorePoints": int(self.score_points),
            "EnterResultsMethod": int(self.enter_results_method),
            "ShowPairNumbers": self.show_pair_numbers,
            "IntermediateResults": self.intermediate_results,
            "AutopoweroffTime": self.autopoweroff_time,
            "VerificationTime": self.verification_time,
            "ShowContract": int(self.show_contract),
            "LeadCard": self.lead_card,
            "MaximumResults": self.maximum_results,
            "MemberNumbers": self.member_numbers,
            "MemberNumbersNoBlankEntry": self.member_numbers_no_blank_entry,
            "BoardOrderVerification": self.board_order_verification,
            "HandRecordValidation": self.hand_record_validation,
            "AutoShutDownBPC": self.auto_shut_down_bpc,
            "BM2PINcode": self.bm2_pi_ncode,
            "BM2ConfirmNP": self.bm2_confirm_np,
            "BM2RemainingBoards": self.bm2_remaining_boards,
            "BM2NextSeatings": self.bm2_next_seatings,
            "BM2ScoreRecap": self.bm2_score_recap,
            "BM2AutoShowScoreRecap": self.bm2_auto_show_score_recap,
            "BM2ScoreCorrection": self.bm2_score_correction,
            "BM2AutoBoardNumber": self.bm2_auto_board_number,
            "BM2FirstBoardManually": self.bm2_first_board_manually,
            "BM2ValidateLeadCard": self.bm2_validate_lead_card,
            "BM2ResultsOverview": int(self.bm2_results_overview),
            "BM2ShowPlayerNames": int(self.bm2_show_player_names),
            "BM2Ranking": int(self.bm2_ranking),
            "BM2GameSummary": self.bm2_game_summary,
            "BM2SummaryPoints": int(self.bm2_summary_points),
            "BM2PairNumberEntry": int(self.bm2_pair_number_entry),
            "BM2ResetFunctionKey": self.bm2_reset_function_key,
            "BM2RecordBidding": self.bm2_record_bidding,
            "BM2RecordPlay": self.bm2_record_play,
            "BM2ValidateRecording": self.bm2_validate_recording,
            "BM2ShowHands": self.bm2_show_hands,
            "NumberValidation": int(self.number_validation),
            "BM2NumberEntryEachRound": self.bm2_number_entry_each_round,
            "BM2NumberEntryPreloadValues": self.bm2_number_entry_preload_values,
            "BM2NameSource": int(self.bm2_name_source),
            "BM2ViewHandRecord": self.bm2_view_hand_record,
            "BM2EnterHandRecord": self.bm2_enter_hand_record,
            "BM2EnterHandRecordWhen": int(self.bm2_enter_hand_record_when),
            "BM2TextBasedNumber": self.bm2_text_based_number,
            "BM2TDCall": self.bm2_td_call,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Bridgemate2SettingsDTO":
        """Builds the DTO from a parsed JSON dict; absent or null values keep the field defaults."""
        dto = cls()
        dto.session_guid = data.get("SessionGuid")
        dto.section_letters = data.get("SectionLetters")
        dto.validation_messages = data.get("ValidationMessages")
        dto.show_results = data["ShowResults"] if data.get("ShowResults") is not None else False
        dto.show_own_result = data["ShowOwnResult"] if data.get("ShowOwnResult") is not None else False
        dto.repeat_results = data["RepeatResults"] if data.get("RepeatResults") is not None else False
        dto.show_percentage = data["ShowPercentage"] if data.get("ShowPercentage") is not None else False
        dto.group_sections = data["GroupSections"] if data.get("GroupSections") is not None else False
        dto.score_points = enum_from_wire(Bm2PointScorePerspectiveOption, data.get("ScorePoints"), Bm2PointScorePerspectiveOption.FromNorthSouth)
        dto.enter_results_method = enum_from_wire(BM2ResultEntryMethod, data.get("EnterResultsMethod"), BM2ResultEntryMethod.UpDownTricks)
        dto.show_pair_numbers = data["ShowPairNumbers"] if data.get("ShowPairNumbers") is not None else False
        dto.intermediate_results = data["IntermediateResults"] if data.get("IntermediateResults") is not None else False
        dto.autopoweroff_time = data["AutopoweroffTime"] if data.get("AutopoweroffTime") is not None else 0
        dto.verification_time = data["VerificationTime"] if data.get("VerificationTime") is not None else 0
        dto.show_contract = enum_from_wire(Bm2ContractRepresentationOption, data.get("ShowContract"), Bm2ContractRepresentationOption.UseSymbols)
        dto.lead_card = data["LeadCard"] if data.get("LeadCard") is not None else False
        dto.maximum_results = data["MaximumResults"] if data.get("MaximumResults") is not None else 0
        dto.member_numbers = data["MemberNumbers"] if data.get("MemberNumbers") is not None else False
        dto.member_numbers_no_blank_entry = data["MemberNumbersNoBlankEntry"] if data.get("MemberNumbersNoBlankEntry") is not None else False
        dto.board_order_verification = data["BoardOrderVerification"] if data.get("BoardOrderVerification") is not None else False
        dto.hand_record_validation = data["HandRecordValidation"] if data.get("HandRecordValidation") is not None else False
        dto.auto_shut_down_bpc = data["AutoShutDownBPC"] if data.get("AutoShutDownBPC") is not None else False
        dto.bm2_pi_ncode = data.get("BM2PINcode")
        dto.bm2_confirm_np = data["BM2ConfirmNP"] if data.get("BM2ConfirmNP") is not None else False
        dto.bm2_remaining_boards = data["BM2RemainingBoards"] if data.get("BM2RemainingBoards") is not None else False
        dto.bm2_next_seatings = data["BM2NextSeatings"] if data.get("BM2NextSeatings") is not None else False
        dto.bm2_score_recap = data["BM2ScoreRecap"] if data.get("BM2ScoreRecap") is not None else False
        dto.bm2_auto_show_score_recap = data["BM2AutoShowScoreRecap"] if data.get("BM2AutoShowScoreRecap") is not None else False
        dto.bm2_score_correction = data["BM2ScoreCorrection"] if data.get("BM2ScoreCorrection") is not None else False
        dto.bm2_auto_board_number = data["BM2AutoBoardNumber"] if data.get("BM2AutoBoardNumber") is not None else False
        dto.bm2_first_board_manually = data["BM2FirstBoardManually"] if data.get("BM2FirstBoardManually") is not None else False
        dto.bm2_validate_lead_card = data["BM2ValidateLeadCard"] if data.get("BM2ValidateLeadCard") is not None else False
        dto.bm2_results_overview = enum_from_wire(Bm2ResultsOverviewOption, data.get("BM2ResultsOverview"), Bm2ResultsOverviewOption.FrequencyList6lines1column)
        dto.bm2_show_player_names = enum_from_wire(Bm2ShowPlayerNamesOption, data.get("BM2ShowPlayerNames"), Bm2ShowPlayerNamesOption.DoNotShow)
        dto.bm2_ranking = enum_from_wire(Bm2ShowRankingOption, data.get("BM2Ranking"), Bm2ShowRankingOption.DoNotShow)
        dto.bm2_game_summary = data["BM2GameSummary"] if data.get("BM2GameSummary") is not None else False
        dto.bm2_summary_points = enum_from_wire(Bm2SummaryPointOption, data.get("BM2SummaryPoints"), Bm2SummaryPointOption.Matchpoints)
        dto.bm2_pair_number_entry = enum_from_wire(Bm2PairNumberEntryOption, data.get("BM2PairNumberEntry"), Bm2PairNumberEntryOption.NoEntry)
        dto.bm2_reset_function_key = data["BM2ResetFunctionKey"] if data.get("BM2ResetFunctionKey") is not None else False
        dto.bm2_record_bidding = data["BM2RecordBidding"] if data.get("BM2RecordBidding") is not None else False
        dto.bm2_record_play = data["BM2RecordPlay"] if data.get("BM2RecordPlay") is not None else False
        dto.bm2_validate_recording = data["BM2ValidateRecording"] if data.get("BM2ValidateRecording") is not None else False
        dto.bm2_show_hands = data["BM2ShowHands"] if data.get("BM2ShowHands") is not None else False
        dto.number_validation = enum_from_wire(Bm2NumberValidationOption, data.get("NumberValidation"), Bm2NumberValidationOption.NoValidation)
        dto.bm2_number_entry_each_round = data["BM2NumberEntryEachRound"] if data.get("BM2NumberEntryEachRound") is not None else False
        dto.bm2_number_entry_preload_values = data["BM2NumberEntryPreloadValues"] if data.get("BM2NumberEntryPreloadValues") is not None else False
        dto.bm2_name_source = enum_from_wire(Bm2NameSource, data.get("BM2NameSource"), Bm2NameSource.PlayerNamesTable)
        dto.bm2_view_hand_record = data["BM2ViewHandRecord"] if data.get("BM2ViewHandRecord") is not None else False
        dto.bm2_enter_hand_record = data["BM2EnterHandRecord"] if data.get("BM2EnterHandRecord") is not None else False
        dto.bm2_enter_hand_record_when = enum_from_wire(Bm2EnterHandrecordWhenOption, data.get("BM2EnterHandRecordWhen"), Bm2EnterHandrecordWhenOption.AtEndOfRound)
        dto.bm2_text_based_number = data["BM2TextBasedNumber"] if data.get("BM2TextBasedNumber") is not None else False
        dto.bm2_td_call = data["BM2TDCall"] if data.get("BM2TDCall") is not None else False
        return dto
