# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from dataclasses import dataclass

from ._support import enum_from_wire
from .bm3_confirm_np_option import Bm3ConfirmNPOption
from .bm3_enter_handrecord_option import Bm3EnterHandrecordOption
from .bm3_language_option import Bm3LanguageOption
from .bm3_lead_card_entry_option import Bm3LeadCardEntryOption
from .bm3_next_round_seating_option import Bm3NextRoundSeatingOption
from .bm3_player_number_mandatory_option import Bm3PlayerNumberMandatoryOption
from .bm3_player_registration_option import Bm3PlayerRegistrationOption
from .bm3_player_registration_option_during_play import Bm3PlayerRegistrationOptionDuringPlay
from .bm3_player_view_option import BM3PlayerViewOption
from .bm3_ranking_display_option import Bm3RankingDisplayOption
from .bm3_result_entry_method import Bm3ResultEntryMethod
from .bm3_result_reentry_option import Bm3ResultReentryOption
from .bm3_score_column_option import Bm3ScoreColumnOption
from .bm3_score_recap_option import Bm3ScoreRecapOption
from .bm3_session_summary_option import Bm3SessionSummaryOption
from .bm3_starting_positions_option import BM3StartingPositionsOption
from .bm3_td_call_option import Bm3TdCallOption
from .bm3_view_handrecord_option import Bm3ViewHandrecordOption
from .bm3_view_percentages_option import Bm3ViewPercentagesOption
from .bm3_view_results_option import Bm3ViewResultsOption
from .bridgemate_settings_dto import BridgemateSettingsDTO


@dataclass
class Bridgemate3SettingsDTO(BridgemateSettingsDTO):
    """Contains all settings for the Bridgemate 3 for a section. Mind that all values must be
    supplied.
    """

    # Valid values 1-7. Defines the screen brightness.
    bm3_screen_brightness: int = 0

    # Valid values 0-15. Defines the number of seconds(times 5) before the screen of the Bridgemate
    # will dim.So the default value of 2 amounts to 10 seconds.
    bm3_screen_dim_mode: int = 0

    # Valid values 0-15. Defines the number of seconds (times 5) before the screen of the Bridgemate
    # will turn off. A value of zero, the default, means "never turn off".
    bm3_screen_off_mode: int = 0

    # Valid values 0-120. Defines the number of seconds (times 5) before the Bridgemate will enter
    # Sleepmode. Once the Bridgemate has entered sleepmode its powerbutton must be used to wake it
    # up again.
    bm3_sleep_mode: int = 0

    # Valid values 0-7. Currently not in use.
    bm3_audio_volume: int = 0

    # Specifies which language the Bridgemate will use. The default is zero for English.
    bm3_language: Bm3LanguageOption = Bm3LanguageOption.English

    # Must be four digits. The code the TD must enter to get access to the TD menu. Defaults to
    # "0000".
    bm3_pi_ncode: str | None = None

    # Specifies if the TD must confirm a "Not Played". Default Off
    bm3_confirm_np: Bm3ConfirmNPOption = Bm3ConfirmNPOption.Disabled

    # Specifies if players can call for the Tournament Director using the Bridgemate.
    bm3_td_call: Bm3TdCallOption = Bm3TdCallOption.Disabled

    # Specifies how players can enter the result for a board: Up/Down tricks, total tricks or
    # American style.
    bm3_result_method: Bm3ResultEntryMethod = Bm3ResultEntryMethod.UpDownTricks

    # Specifies if players may reenter the result of the board after the original entry has been
    # confirmed by the opponents.
    bm3_board_result_reentry: Bm3ResultReentryOption = Bm3ResultReentryOption.Disabled

    # Specifies if the leadcard must be enterd together with the contract and if the leadcard should
    # be validated againts the handrecord.
    bm3_lead_card_entry: Bm3LeadCardEntryOption = Bm3LeadCardEntryOption.Disabled

    # Specifies if and when the players can make themselves known by entering their playernumber
    # and/or name on the Bridgemate.
    bm3_player_number_entry: Bm3PlayerRegistrationOption = Bm3PlayerRegistrationOption.Disabled

    # Specifies if and when the players can make themselves known by entering their playernumber
    # and/or name on the Bridgemate while the round is in progress (i.e.: after a board has been
    # entered).
    bm3_player_number_entry_during_play: Bm3PlayerRegistrationOptionDuringPlay = Bm3PlayerRegistrationOptionDuringPlay.Disabled

    # Specifies if players must identify themselves at the start of the session by entering their
    # playernumber.
    bm3_player_number_mandatory: Bm3PlayerNumberMandatoryOption = Bm3PlayerNumberMandatoryOption.Disabled

    # Specifies whether starting positions should be confirmed by players at start of the session
    bm3_starting_positions: BM3StartingPositionsOption = BM3StartingPositionsOption.Disabled

    # Specifies how the wind rose player view is displayed
    bm3_player_view: BM3PlayerViewOption = BM3PlayerViewOption.NorthOnTop

    # Specifies if and when the Bridgemate will show the current ranking for the players on the
    # table.
    bm3_ranking: Bm3RankingDisplayOption = Bm3RankingDisplayOption.Disabled

    # Specifes if the seatings for the next round must be displayed after the last result has been
    # entered for the round.
    bm3_next_seatings: Bm3NextRoundSeatingOption = Bm3NextRoundSeatingOption.Disabled

    # Specifies if and when the Bridgemate will show a recap of the scores obtained on the table in
    # the current round.
    bm3_score_recap: Bm3ScoreRecapOption = Bm3ScoreRecapOption.Disabled

    # Specifies if the Bridgemate will show the other results for the board that was just entered.
    bm3_view_results: Bm3ViewResultsOption = Bm3ViewResultsOption.Disabled

    # Specifies if the Bridgemate will show a session summary with all the scores obtained in the
    # session once the session has ended.
    bm3_session_summary: Bm3SessionSummaryOption = Bm3SessionSummaryOption.Disabled

    # Specifies if the score columns should be for NS only (one column) or for NS and EW (two
    # columns)
    bm3_score_colum: Bm3ScoreColumnOption = Bm3ScoreColumnOption.NorthSouthOnly

    # Specifies if the own percentage should be included in the results overview.
    bm_view_percentages: Bm3ViewPercentagesOption = Bm3ViewPercentagesOption.Disabled

    # Specifies if players may view the handrecord after the result has been entered.
    bm3_view_handrecord: Bm3ViewHandrecordOption = Bm3ViewHandrecordOption.Disabled

    # Specifies if and when the players can enter the handrecord for a board if it is not present.
    bm3_enter_handrecord: Bm3EnterHandrecordOption = Bm3EnterHandrecordOption.Disabled

    def to_dict(self) -> dict:
        """The JSON-ready dict with the PascalCase wire names, in wire order."""
        return {
            "SessionGuid": self.session_guid,
            "SectionLetters": self.section_letters,
            "ValidationMessages": self.validation_messages,
            "BM3ScreenBrightness": self.bm3_screen_brightness,
            "BM3ScreenDimMode": self.bm3_screen_dim_mode,
            "BM3ScreenOffMode": self.bm3_screen_off_mode,
            "BM3SleepMode": self.bm3_sleep_mode,
            "BM3AudioVolume": self.bm3_audio_volume,
            "BM3Language": int(self.bm3_language),
            "BM3PINcode": self.bm3_pi_ncode,
            "BM3ConfirmNP": int(self.bm3_confirm_np),
            "BM3TDCall": int(self.bm3_td_call),
            "BM3ResultMethod": int(self.bm3_result_method),
            "BM3BoardResultReentry": int(self.bm3_board_result_reentry),
            "BM3LeadCardEntry": int(self.bm3_lead_card_entry),
            "BM3PlayerNumberEntry": int(self.bm3_player_number_entry),
            "BM3PlayerNumberEntryDuringPlay": int(self.bm3_player_number_entry_during_play),
            "BM3PlayerNumberMandatory": int(self.bm3_player_number_mandatory),
            "BM3StartingPositions": int(self.bm3_starting_positions),
            "BM3PlayerView": int(self.bm3_player_view),
            "BM3Ranking": int(self.bm3_ranking),
            "BM3NextSeatings": int(self.bm3_next_seatings),
            "BM3ScoreRecap": int(self.bm3_score_recap),
            "BM3ViewResults": int(self.bm3_view_results),
            "BM3SessionSummary": int(self.bm3_session_summary),
            "BM3ScoreColum": int(self.bm3_score_colum),
            "BMViewPercentages": int(self.bm_view_percentages),
            "BM3ViewHandrecord": int(self.bm3_view_handrecord),
            "BM3EnterHandrecord": int(self.bm3_enter_handrecord),
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Bridgemate3SettingsDTO":
        """Builds the DTO from a parsed JSON dict; absent or null values keep the field defaults."""
        dto = cls()
        dto.session_guid = data.get("SessionGuid")
        dto.section_letters = data.get("SectionLetters")
        dto.validation_messages = data.get("ValidationMessages")
        dto.bm3_screen_brightness = data["BM3ScreenBrightness"] if data.get("BM3ScreenBrightness") is not None else 0
        dto.bm3_screen_dim_mode = data["BM3ScreenDimMode"] if data.get("BM3ScreenDimMode") is not None else 0
        dto.bm3_screen_off_mode = data["BM3ScreenOffMode"] if data.get("BM3ScreenOffMode") is not None else 0
        dto.bm3_sleep_mode = data["BM3SleepMode"] if data.get("BM3SleepMode") is not None else 0
        dto.bm3_audio_volume = data["BM3AudioVolume"] if data.get("BM3AudioVolume") is not None else 0
        dto.bm3_language = enum_from_wire(Bm3LanguageOption, data.get("BM3Language"), Bm3LanguageOption.English)
        dto.bm3_pi_ncode = data.get("BM3PINcode")
        dto.bm3_confirm_np = enum_from_wire(Bm3ConfirmNPOption, data.get("BM3ConfirmNP"), Bm3ConfirmNPOption.Disabled)
        dto.bm3_td_call = enum_from_wire(Bm3TdCallOption, data.get("BM3TDCall"), Bm3TdCallOption.Disabled)
        dto.bm3_result_method = enum_from_wire(Bm3ResultEntryMethod, data.get("BM3ResultMethod"), Bm3ResultEntryMethod.UpDownTricks)
        dto.bm3_board_result_reentry = enum_from_wire(Bm3ResultReentryOption, data.get("BM3BoardResultReentry"), Bm3ResultReentryOption.Disabled)
        dto.bm3_lead_card_entry = enum_from_wire(Bm3LeadCardEntryOption, data.get("BM3LeadCardEntry"), Bm3LeadCardEntryOption.Disabled)
        dto.bm3_player_number_entry = enum_from_wire(Bm3PlayerRegistrationOption, data.get("BM3PlayerNumberEntry"), Bm3PlayerRegistrationOption.Disabled)
        dto.bm3_player_number_entry_during_play = enum_from_wire(Bm3PlayerRegistrationOptionDuringPlay, data.get("BM3PlayerNumberEntryDuringPlay"), Bm3PlayerRegistrationOptionDuringPlay.Disabled)
        dto.bm3_player_number_mandatory = enum_from_wire(Bm3PlayerNumberMandatoryOption, data.get("BM3PlayerNumberMandatory"), Bm3PlayerNumberMandatoryOption.Disabled)
        dto.bm3_starting_positions = enum_from_wire(BM3StartingPositionsOption, data.get("BM3StartingPositions"), BM3StartingPositionsOption.Disabled)
        dto.bm3_player_view = enum_from_wire(BM3PlayerViewOption, data.get("BM3PlayerView"), BM3PlayerViewOption.NorthOnTop)
        dto.bm3_ranking = enum_from_wire(Bm3RankingDisplayOption, data.get("BM3Ranking"), Bm3RankingDisplayOption.Disabled)
        dto.bm3_next_seatings = enum_from_wire(Bm3NextRoundSeatingOption, data.get("BM3NextSeatings"), Bm3NextRoundSeatingOption.Disabled)
        dto.bm3_score_recap = enum_from_wire(Bm3ScoreRecapOption, data.get("BM3ScoreRecap"), Bm3ScoreRecapOption.Disabled)
        dto.bm3_view_results = enum_from_wire(Bm3ViewResultsOption, data.get("BM3ViewResults"), Bm3ViewResultsOption.Disabled)
        dto.bm3_session_summary = enum_from_wire(Bm3SessionSummaryOption, data.get("BM3SessionSummary"), Bm3SessionSummaryOption.Disabled)
        dto.bm3_score_colum = enum_from_wire(Bm3ScoreColumnOption, data.get("BM3ScoreColum"), Bm3ScoreColumnOption.NorthSouthOnly)
        dto.bm_view_percentages = enum_from_wire(Bm3ViewPercentagesOption, data.get("BMViewPercentages"), Bm3ViewPercentagesOption.Disabled)
        dto.bm3_view_handrecord = enum_from_wire(Bm3ViewHandrecordOption, data.get("BM3ViewHandrecord"), Bm3ViewHandrecordOption.Disabled)
        dto.bm3_enter_handrecord = enum_from_wire(Bm3EnterHandrecordOption, data.get("BM3EnterHandrecord"), Bm3EnterHandrecordOption.Disabled)
        return dto
