# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from dataclasses import dataclass



@dataclass
class BridgemateSettingsDTO:
    """The base class for the Bridgemate2SettingsDTO and the Bridgemate3SettingsDTO"""

    # Required. Specifies the guid of the session for which the settings apply.
    session_guid: str | None = None

    # Required. Specifies for which section the settings apply.
    section_letters: str | None = None

    # An array of messages describing problems in data integrity and invalid values.
    validation_messages: list[str] | None = None
