# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from dataclasses import dataclass



@dataclass
class ContinueDTO:
    """Instructs BCS to continue working with a previously created event using the
    ScoringProgramPipeClient.Continue method or the ScoringProgramPipeClient.ContinueAsync
    method.
    """

    # Tells BCS which event to continue. When there is only one session the event guid will be its
    # session guid unless it was set to a different value in the original InitDTO.
    event_guid: str | None = None

    # Required when using the http interface for the dataconnector
    club_id: str | None = None

    # 1: Just start BCS and let it reconnect to the last used scoring file if it contains a session
    # with the correct guid. 5: Start BCS, let it reconnect and start reading. add 128: clear all
    # previous data from the Data Connector.
    commands: int = 0

    # Optional. Specifies a different directory for the BCS scoring file. Only use in advanced
    # scenarios. If used make sure that the directory exists.
    alternative_data_folder: str | None = None

    def to_dict(self) -> dict:
        """The JSON-ready dict with the PascalCase wire names, in wire order."""
        return {
            "EventGuid": self.event_guid,
            "ClubId": self.club_id,
            "Commands": self.commands,
            "AlternativeDataFolder": self.alternative_data_folder,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ContinueDTO":
        """Builds the DTO from a parsed JSON dict; absent or null values keep the field defaults."""
        dto = cls()
        dto.event_guid = data.get("EventGuid")
        dto.club_id = data.get("ClubId")
        dto.commands = data["Commands"] if data.get("Commands") is not None else 0
        dto.alternative_data_folder = data.get("AlternativeDataFolder")
        return dto
