# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from dataclasses import dataclass



@dataclass
class HandrecordDTO:
    """Contains the data for a handrecord and optionally its double dummy values."""

    # Required. The guid of the session the handrecord belongs to. A string built from a Guid,
    # without the curly braces or connecting dashes. The letters must be capitals. Must be unique
    session_guid: str | None = None

    # Required. The number of the scoringgroup that the handrecord belongs to.
    scoring_group_number: int = 0

    # Required, any of the sections that are part of the scoringgroup.
    section_letters: str | None = None

    # Required. Must be greater than zero.
    board_number: int = 0

    # Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
    # disqualified.
    north_clubs: str | None = None

    # Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
    # disqualified.
    north_diamonds: str | None = None

    # Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
    # disqualified.
    north_hearts: str | None = None

    # Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
    # disqualified.
    north_spades: str | None = None

    # Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
    # disqualified.
    east_clubs: str | None = None

    # Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
    # disqualified.
    east_diamonds: str | None = None

    # Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
    # disqualified.
    east_hearts: str | None = None

    # Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
    # disqualified.
    east_spades: str | None = None

    # Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
    # disqualified.
    south_clubs: str | None = None

    # Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
    # disqualified.
    south_diamonds: str | None = None

    # Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
    # disqualified.
    south_hearts: str | None = None

    # Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
    # disqualified.
    south_spades: str | None = None

    # Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
    # disqualified.
    west_clubs: str | None = None

    # Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
    # disqualified.
    west_diamonds: str | None = None

    # Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
    # disqualified.
    west_hearts: str | None = None

    # Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
    # disqualified.
    west_spades: str | None = None

    # It "True" the double dummy values will be processed by the Data Connector.
    has_hand_evaluation_data: bool = False

    # The number of tricks that can be made with North as declarer and Clubs as denomination.
    double_dummy_north_clubs: int = 0

    # The number of tricks that can be made with North as declarer and Diamonds as denomination.
    double_dummy_north_diamonds: int = 0

    # The number of tricks that can be made with North as declarer and Hearts as denomination.
    double_dummy_north_hearts: int = 0

    # The number of tricks that can be made with North as declarer and Spades as denomination.
    double_dummy_north_spades: int = 0

    # The number of tricks that can be made with North as declarer and No Trump as denomination.
    double_dummy_north_no_trump: int = 0

    # The number of tricks that can be made with East as declarer and Clubs as denomination.
    double_dummy_east_clubs: int = 0

    # The number of tricks that can be made with East as declarer and Diamonds as denomination.
    double_dummy_east_diamonds: int = 0

    # The number of tricks that can be made with East as declarer and Hearts as denomination.
    double_dummy_east_hearts: int = 0

    # The number of tricks that can be made with East as declarer and Spades as denomination.
    double_dummy_east_spades: int = 0

    # The number of tricks that can be made with East as declarer and No Trump as denomination.
    double_dummy_east_no_trump: int = 0

    # The number of tricks that can be made with South as declarer and Clubs as denomination.
    double_dummy_south_clubs: int = 0

    # The number of tricks that can be made with South as declarer and Diamonds as denomination.
    double_dummy_south_diamonds: int = 0

    # The number of tricks that can be made with South as declarer and Hearts as denomination.
    double_dummy_south_hearts: int = 0

    # The number of tricks that can be made with South as declarer and Spades as denomination.
    double_dummy_south_spades: int = 0

    # The number of tricks that can be made with South as declarer and No Trump as denomination.
    double_dummy_south_no_trump: int = 0

    # The number of tricks that can be made with West as declarer and Clubs as denomination.
    double_dummy_west_clubs: int = 0

    # The number of tricks that can be made with West as declarer and Diamonds as denomination.
    double_dummy_west_diamonds: int = 0

    # The number of tricks that can be made with West as declarer and Hearts as denomination.
    double_dummy_west_hearts: int = 0

    # The number of tricks that can be made with West as declarer and Spades as denomination.
    double_dummy_west_spades: int = 0

    # The number of tricks that can be made with West as declarer and No Trump as denomination.
    double_dummy_west_no_trump: int = 0

    # An array of messages describing problems in data integrity and invalid values.
    validation_messages: list[str] | None = None

    def to_dict(self) -> dict:
        """The JSON-ready dict with the PascalCase wire names, in wire order."""
        return {
            "SessionGuid": self.session_guid,
            "ScoringGroupNumber": self.scoring_group_number,
            "SectionLetters": self.section_letters,
            "BoardNumber": self.board_number,
            "NorthClubs": self.north_clubs,
            "NorthDiamonds": self.north_diamonds,
            "NorthHearts": self.north_hearts,
            "NorthSpades": self.north_spades,
            "EastClubs": self.east_clubs,
            "EastDiamonds": self.east_diamonds,
            "EastHearts": self.east_hearts,
            "EastSpades": self.east_spades,
            "SouthClubs": self.south_clubs,
            "SouthDiamonds": self.south_diamonds,
            "SouthHearts": self.south_hearts,
            "SouthSpades": self.south_spades,
            "WestClubs": self.west_clubs,
            "WestDiamonds": self.west_diamonds,
            "WestHearts": self.west_hearts,
            "WestSpades": self.west_spades,
            "HasHandEvaluationData": self.has_hand_evaluation_data,
            "DoubleDummyNorthClubs": self.double_dummy_north_clubs,
            "DoubleDummyNorthDiamonds": self.double_dummy_north_diamonds,
            "DoubleDummyNorthHearts": self.double_dummy_north_hearts,
            "DoubleDummyNorthSpades": self.double_dummy_north_spades,
            "DoubleDummyNorthNoTrump": self.double_dummy_north_no_trump,
            "DoubleDummyEastClubs": self.double_dummy_east_clubs,
            "DoubleDummyEastDiamonds": self.double_dummy_east_diamonds,
            "DoubleDummyEastHearts": self.double_dummy_east_hearts,
            "DoubleDummyEastSpades": self.double_dummy_east_spades,
            "DoubleDummyEastNoTrump": self.double_dummy_east_no_trump,
            "DoubleDummySouthClubs": self.double_dummy_south_clubs,
            "DoubleDummySouthDiamonds": self.double_dummy_south_diamonds,
            "DoubleDummySouthHearts": self.double_dummy_south_hearts,
            "DoubleDummySouthSpades": self.double_dummy_south_spades,
            "DoubleDummySouthNoTrump": self.double_dummy_south_no_trump,
            "DoubleDummyWestClubs": self.double_dummy_west_clubs,
            "DoubleDummyWestDiamonds": self.double_dummy_west_diamonds,
            "DoubleDummyWestHearts": self.double_dummy_west_hearts,
            "DoubleDummyWestSpades": self.double_dummy_west_spades,
            "DoubleDummyWestNoTrump": self.double_dummy_west_no_trump,
            "ValidationMessages": self.validation_messages,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "HandrecordDTO":
        """Builds the DTO from a parsed JSON dict; absent or null values keep the field defaults."""
        dto = cls()
        dto.session_guid = data.get("SessionGuid")
        dto.scoring_group_number = data["ScoringGroupNumber"] if data.get("ScoringGroupNumber") is not None else 0
        dto.section_letters = data.get("SectionLetters")
        dto.board_number = data["BoardNumber"] if data.get("BoardNumber") is not None else 0
        dto.north_clubs = data.get("NorthClubs")
        dto.north_diamonds = data.get("NorthDiamonds")
        dto.north_hearts = data.get("NorthHearts")
        dto.north_spades = data.get("NorthSpades")
        dto.east_clubs = data.get("EastClubs")
        dto.east_diamonds = data.get("EastDiamonds")
        dto.east_hearts = data.get("EastHearts")
        dto.east_spades = data.get("EastSpades")
        dto.south_clubs = data.get("SouthClubs")
        dto.south_diamonds = data.get("SouthDiamonds")
        dto.south_hearts = data.get("SouthHearts")
        dto.south_spades = data.get("SouthSpades")
        dto.west_clubs = data.get("WestClubs")
        dto.west_diamonds = data.get("WestDiamonds")
        dto.west_hearts = data.get("WestHearts")
        dto.west_spades = data.get("WestSpades")
        dto.has_hand_evaluation_data = data["HasHandEvaluationData"] if data.get("HasHandEvaluationData") is not None else False
        dto.double_dummy_north_clubs = data["DoubleDummyNorthClubs"] if data.get("DoubleDummyNorthClubs") is not None else 0
        dto.double_dummy_north_diamonds = data["DoubleDummyNorthDiamonds"] if data.get("DoubleDummyNorthDiamonds") is not None else 0
        dto.double_dummy_north_hearts = data["DoubleDummyNorthHearts"] if data.get("DoubleDummyNorthHearts") is not None else 0
        dto.double_dummy_north_spades = data["DoubleDummyNorthSpades"] if data.get("DoubleDummyNorthSpades") is not None else 0
        dto.double_dummy_north_no_trump = data["DoubleDummyNorthNoTrump"] if data.get("DoubleDummyNorthNoTrump") is not None else 0
        dto.double_dummy_east_clubs = data["DoubleDummyEastClubs"] if data.get("DoubleDummyEastClubs") is not None else 0
        dto.double_dummy_east_diamonds = data["DoubleDummyEastDiamonds"] if data.get("DoubleDummyEastDiamonds") is not None else 0
        dto.double_dummy_east_hearts = data["DoubleDummyEastHearts"] if data.get("DoubleDummyEastHearts") is not None else 0
        dto.double_dummy_east_spades = data["DoubleDummyEastSpades"] if data.get("DoubleDummyEastSpades") is not None else 0
        dto.double_dummy_east_no_trump = data["DoubleDummyEastNoTrump"] if data.get("DoubleDummyEastNoTrump") is not None else 0
        dto.double_dummy_south_clubs = data["DoubleDummySouthClubs"] if data.get("DoubleDummySouthClubs") is not None else 0
        dto.double_dummy_south_diamonds = data["DoubleDummySouthDiamonds"] if data.get("DoubleDummySouthDiamonds") is not None else 0
        dto.double_dummy_south_hearts = data["DoubleDummySouthHearts"] if data.get("DoubleDummySouthHearts") is not None else 0
        dto.double_dummy_south_spades = data["DoubleDummySouthSpades"] if data.get("DoubleDummySouthSpades") is not None else 0
        dto.double_dummy_south_no_trump = data["DoubleDummySouthNoTrump"] if data.get("DoubleDummySouthNoTrump") is not None else 0
        dto.double_dummy_west_clubs = data["DoubleDummyWestClubs"] if data.get("DoubleDummyWestClubs") is not None else 0
        dto.double_dummy_west_diamonds = data["DoubleDummyWestDiamonds"] if data.get("DoubleDummyWestDiamonds") is not None else 0
        dto.double_dummy_west_hearts = data["DoubleDummyWestHearts"] if data.get("DoubleDummyWestHearts") is not None else 0
        dto.double_dummy_west_spades = data["DoubleDummyWestSpades"] if data.get("DoubleDummyWestSpades") is not None else 0
        dto.double_dummy_west_no_trump = data["DoubleDummyWestNoTrump"] if data.get("DoubleDummyWestNoTrump") is not None else 0
        dto.validation_messages = data.get("ValidationMessages")
        return dto
