# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from dataclasses import dataclass

from .bridgemate2_settings_dto import Bridgemate2SettingsDTO
from .bridgemate3_settings_dto import Bridgemate3SettingsDTO
from .handrecord_dto import HandrecordDTO
from .participation_dto import ParticipationDTO
from .player_data_dto import PlayerDataDTO
from .session_dto import SessionDTO


@dataclass
class InitDTO:
    """Contains information on how to construct a new event, with its sessions, sections, tables
    and rounds. Optionally player data, participations and handrecords can be added. Doing this
    is more performant than adding them later. Is used as a parameter for the
    ScoringProgramPipeClient.Initialize or the ScoringProgramPipeClient.InitializeAsync method.
    """

    # Instructs the Data Connector to start BCS.
    StartBCS = 1

    # Instructs BCS to create a new event from the data in this DTO.
    Command_Reset = 2

    # Instructs BCS to start reading from the Data Connector.
    Command_StartReading = 4

    # Instructs BCS to upload the sessions to the Bridgemate App server.
    Command_ShowInApp = 8

    # Instructs BCS to start minimized.
    Command_Minimize = 16

    # Instructs BCS to shut down after the last result has been processed.
    Command_AutoShutDownBPC = 32

    # Sets the log level to "Debug" rather than "Info".
    Command_LogLevel_Debug = 64

    # Instructs the Data Connector to clear all its previous data and start with a clean slate.
    Command_ClearData = 128

    # Instructs the Data Connector to use communicate over http.
    Command_UseHttp = 256

    # Instructions to BCS. Add up the values to combine. 1. Start BCS (if not already started). 2:
    # Reset the Bridgemates (and App) and fill them with the provided data. 4: Start Reading from
    # the Bridgemates, Data Connector (and App). 8: Upload the sessions to the app. 16: Minimize BCS
    # 32:Close BCS when all results have been processed. 64: Lower the logging level from "Info" to
    # "Debug". 128:Clear all previous data from the Data Connector queue.
    commands: int = 0

    # Required if the number of sessions is greater than one. This signals that BCS should
    # administer these sessions together.
    event_guid: str | None = None

    # Required when using http for communication with the data connector.
    club_id: str | None = None

    # Optional. Specifies a different directory for the BCS scoring file. Only use in advanced
    # scenarios. If used make sure that the directory exists.
    alternative_data_folder: str | None = None

    # Required, must be at least one.
    sessions: list[SessionDTO] | None = None

    # Optional: the data of at least the players that will participate in the sessions. Player data
    # is required for every participation that has its a SessionGuid and PlayerNumber properties
    # set.
    player_data: list[PlayerDataDTO] | None = None

    # Optional. Each participation with its SessionGuid and PlayerNumber properties set must have a
    # corresponding player data element that specifies at least its name.
    participations: list[ParticipationDTO] | None = None

    # Optional. The handrecords for each session.
    handrecords: list[HandrecordDTO] | None = None

    # Optional. The settings for the Bridgemate 2 for all sections (if in use).
    bridgemate2_settings: list[Bridgemate2SettingsDTO] | None = None

    # Optional. The settings for the Bridgemate 3 for all sections (if in use).
    bridgemate3_settings: list[Bridgemate3SettingsDTO] | None = None

    # An array of messages describing problems in data integrity and invalid values.
    validation_messages: list[str] | None = None

    def to_dict(self) -> dict:
        """The JSON-ready dict with the PascalCase wire names, in wire order."""
        return {
            "Commands": self.commands,
            "EventGuid": self.event_guid,
            "ClubId": self.club_id,
            "AlternativeDataFolder": self.alternative_data_folder,
            "Sessions": [item.to_dict() for item in self.sessions] if self.sessions is not None else None,
            "PlayerData": [item.to_dict() for item in self.player_data] if self.player_data is not None else None,
            "Participations": [item.to_dict() for item in self.participations] if self.participations is not None else None,
            "Handrecords": [item.to_dict() for item in self.handrecords] if self.handrecords is not None else None,
            "Bridgemate2Settings": [item.to_dict() for item in self.bridgemate2_settings] if self.bridgemate2_settings is not None else None,
            "Bridgemate3Settings": [item.to_dict() for item in self.bridgemate3_settings] if self.bridgemate3_settings is not None else None,
            "ValidationMessages": self.validation_messages,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "InitDTO":
        """Builds the DTO from a parsed JSON dict; absent or null values keep the field defaults."""
        dto = cls()
        dto.commands = data["Commands"] if data.get("Commands") is not None else 0
        dto.event_guid = data.get("EventGuid")
        dto.club_id = data.get("ClubId")
        dto.alternative_data_folder = data.get("AlternativeDataFolder")
        dto.sessions = [SessionDTO.from_dict(item) for item in data["Sessions"]] if data.get("Sessions") is not None else None
        dto.player_data = [PlayerDataDTO.from_dict(item) for item in data["PlayerData"]] if data.get("PlayerData") is not None else None
        dto.participations = [ParticipationDTO.from_dict(item) for item in data["Participations"]] if data.get("Participations") is not None else None
        dto.handrecords = [HandrecordDTO.from_dict(item) for item in data["Handrecords"]] if data.get("Handrecords") is not None else None
        dto.bridgemate2_settings = [Bridgemate2SettingsDTO.from_dict(item) for item in data["Bridgemate2Settings"]] if data.get("Bridgemate2Settings") is not None else None
        dto.bridgemate3_settings = [Bridgemate3SettingsDTO.from_dict(item) for item in data["Bridgemate3Settings"]] if data.get("Bridgemate3Settings") is not None else None
        dto.validation_messages = data.get("ValidationMessages")
        return dto
