# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from dataclasses import dataclass

from ._support import enum_from_wire
from .table_direction import TableDirection


@dataclass
class ParticipationDTO:
    """This class can be used: 1. To give names for the players in the first round by only
    specifying their player numbers. For this to work the names belonging to the playernumber
    must have been passed first using PlayerDTO's. 2. To give names for the players in the first
    round by omitting their playernumber. In this case the players will be registerd for this
    session only. The combination of both playernumber and name details is not supported.
    """

    # Required. The guid of the session the participation belongs to. A string built from a Guid,
    # without the curly braces or connecting dashes. The letters must be capitals
    session_guid: str | None = None

    # Required. The letters of the section the participation belongs to. Can be A-Z, AA, BB,
    # CC,...ZZ, AAA, BBB, CCC, ... ZZZ
    section_letters: str | None = None

    # Required. The number of the table for the player in the round.
    table_number: int = 0

    # Required. The position on the table for the player in the round. 1: North 2: East 3: South 4:
    # West
    direction: TableDirection = TableDirection.None_

    # Currently only the values zero and one are supported. They are treated the same as the table
    # where the player sits in the first round. Optional, specifying a number higher than 1
    # indicates that the name of the player has become known in a latter round. BCS will use the
    # known movement to calculate the player's positions in other rounds.
    round_number: int = 0

    # Optional, but must be present together with the SessionGuid if no name details are passed. The
    # playernumber must have been passed beforehand using a PlayerDTO containg the name details.
    player_number: str | None = None

    # Signals that this player was swapped with his partner: North was swapped with South, or East
    # with West.
    is_player_swap: bool = False

    # Optional, must only be used when the playernumber is empty.
    first_name: str | None = None

    # Required when the playernumber is empty.Must only be used when the playernumber is empty.
    last_name: str | None = None

    # Optional, must only be used when the playernumber is empty.
    country_code: str | None = None

    # An array of messages describing problems in data integrity and invalid values.
    validation_messages: list[str] | None = None

    def to_dict(self) -> dict:
        """The JSON-ready dict with the PascalCase wire names, in wire order."""
        return {
            "SessionGuid": self.session_guid,
            "SectionLetters": self.section_letters,
            "TableNumber": self.table_number,
            "Direction": int(self.direction),
            "RoundNumber": self.round_number,
            "PlayerNumber": self.player_number,
            "IsPlayerSwap": self.is_player_swap,
            "FirstName": self.first_name,
            "LastName": self.last_name,
            "CountryCode": self.country_code,
            "ValidationMessages": self.validation_messages,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ParticipationDTO":
        """Builds the DTO from a parsed JSON dict; absent or null values keep the field defaults."""
        dto = cls()
        dto.session_guid = data.get("SessionGuid")
        dto.section_letters = data.get("SectionLetters")
        dto.table_number = data["TableNumber"] if data.get("TableNumber") is not None else 0
        dto.direction = enum_from_wire(TableDirection, data.get("Direction"), TableDirection.None_)
        dto.round_number = data["RoundNumber"] if data.get("RoundNumber") is not None else 0
        dto.player_number = data.get("PlayerNumber")
        dto.is_player_swap = data["IsPlayerSwap"] if data.get("IsPlayerSwap") is not None else False
        dto.first_name = data.get("FirstName")
        dto.last_name = data.get("LastName")
        dto.country_code = data.get("CountryCode")
        dto.validation_messages = data.get("ValidationMessages")
        return dto
