# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from dataclasses import dataclass



@dataclass
class PlayerDataDTO:
    """This class carries information on a player: name, country and playernumber. Each
    ParticipationDTO carrying a non empty playernumber property must have a corresponding
    PlayerDataDTO woith the given playernumber (and SessionGuid) that was sent before the
    ParticipationDTO was sent.
    """

    # Required, the guid of the session the player participates in.
    session_guid: str | None = None

    # Required when using the http interface for the dataconnector
    club_id: str | None = None

    # Required, must uniquely identify the player within the session.
    player_number: str | None = None

    # Optional
    first_name: str | None = None

    # Required
    last_name: str | None = None

    # Optional
    country_code: str | None = None

    # An array of messages describing problems in data integrity and invalid values.
    validation_messages: list[str] | None = None

    def to_dict(self) -> dict:
        """The JSON-ready dict with the PascalCase wire names, in wire order."""
        return {
            "SessionGuid": self.session_guid,
            "ClubId": self.club_id,
            "PlayerNumber": self.player_number,
            "FirstName": self.first_name,
            "LastName": self.last_name,
            "CountryCode": self.country_code,
            "ValidationMessages": self.validation_messages,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "PlayerDataDTO":
        """Builds the DTO from a parsed JSON dict; absent or null values keep the field defaults."""
        dto = cls()
        dto.session_guid = data.get("SessionGuid")
        dto.club_id = data.get("ClubId")
        dto.player_number = data.get("PlayerNumber")
        dto.first_name = data.get("FirstName")
        dto.last_name = data.get("LastName")
        dto.country_code = data.get("CountryCode")
        dto.validation_messages = data.get("ValidationMessages")
        return dto
