# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from dataclasses import dataclass



@dataclass
class RoundDTO:
    """The RoundDTO describes the seating for a round on a table: the NS and EW pairs and the board
    numbers expressed by the LowBoardNumber and HighBoardNumber properties.
    """

    # Required. The guid of the session the round belongs to.
    session_guid: str | None = None

    # Required, the letters of the section.
    section_letters: str | None = None

    # Required, must be greater than zero.
    table_number: int = 0

    # Required, must be greater than zero.
    round_number: int = 0

    # Optional, can be zero if the table is empty (has no pairs) or is a sit-out (One pair is
    # absent).
    low_board_number: int = 0

    # Optional, can be zero if the table is empty (has no pairs) or is a sit-out (One pair is
    # absent).
    high_board_number: int = 0

    # Required, can be zero if the table is empty or the opponents have a sit-out.
    pair_ns: int = 0

    # Required, can be zero if the table is empty or the opponents have a sit-out.
    pair_ew: int = 0

    # Optional. The number of the team the NS pair belongs to.
    team_ns: int = 0

    # Optional. The number of the team the EW pair belongs to.
    team_ew: int = 0

    # Optional. The letters of the section where the teammates play the same boards. If used the
    # MatesTableNumber and MatesTableRoundNumber properties must be set as well.
    mates_table_section_letters: str | None = None

    # Optional. The number of the table where the teammates play the same boards. If used the
    # MatesTableSectionLetters and MatesTableRoundNumber properties must be set as well.
    mates_table_table_number: int = 0

    # Optional. The number of the round where the teammates play the same boards. If used the
    # MatesTableSectionLetters and the MatesTableNumber properties must be set as well.
    mates_table_round_number: int = 0

    # Currently not in use for scoring programs. Used for internal administration when handling
    # movement updates.
    updated: bool = False

    # An array of messages describing problems in data integrity and invalid values.
    validation_messages: list[str] | None = None

    def to_dict(self) -> dict:
        """The JSON-ready dict with the PascalCase wire names, in wire order."""
        return {
            "SessionGuid": self.session_guid,
            "SectionLetters": self.section_letters,
            "TableNumber": self.table_number,
            "RoundNumber": self.round_number,
            "LowBoardNumber": self.low_board_number,
            "HighBoardNumber": self.high_board_number,
            "PairNS": self.pair_ns,
            "PairEW": self.pair_ew,
            "TeamNS": self.team_ns,
            "TeamEW": self.team_ew,
            "MatesTableSectionLetters": self.mates_table_section_letters,
            "MatesTableTableNumber": self.mates_table_table_number,
            "MatesTableRoundNumber": self.mates_table_round_number,
            "Updated": self.updated,
            "ValidationMessages": self.validation_messages,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "RoundDTO":
        """Builds the DTO from a parsed JSON dict; absent or null values keep the field defaults."""
        dto = cls()
        dto.session_guid = data.get("SessionGuid")
        dto.section_letters = data.get("SectionLetters")
        dto.table_number = data["TableNumber"] if data.get("TableNumber") is not None else 0
        dto.round_number = data["RoundNumber"] if data.get("RoundNumber") is not None else 0
        dto.low_board_number = data["LowBoardNumber"] if data.get("LowBoardNumber") is not None else 0
        dto.high_board_number = data["HighBoardNumber"] if data.get("HighBoardNumber") is not None else 0
        dto.pair_ns = data["PairNS"] if data.get("PairNS") is not None else 0
        dto.pair_ew = data["PairEW"] if data.get("PairEW") is not None else 0
        dto.team_ns = data["TeamNS"] if data.get("TeamNS") is not None else 0
        dto.team_ew = data["TeamEW"] if data.get("TeamEW") is not None else 0
        dto.mates_table_section_letters = data.get("MatesTableSectionLetters")
        dto.mates_table_table_number = data["MatesTableTableNumber"] if data.get("MatesTableTableNumber") is not None else 0
        dto.mates_table_round_number = data["MatesTableRoundNumber"] if data.get("MatesTableRoundNumber") is not None else 0
        dto.updated = data["Updated"] if data.get("Updated") is not None else False
        dto.validation_messages = data.get("ValidationMessages")
        return dto
