# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from dataclasses import dataclass

from .section_dto import SectionDTO


@dataclass
class ScoringGroupDTO:
    """The scoring group holds information on the scoring method of its sections. A scoring group
    must have at least one section, though this can be omitted when using this DTO for scoring
    group updates. If a scoring group has more than one section the score calculation will treat
    these sections as if they were one.
    """

    # The matchscore is expressed in matchpoints.
    ScoringType_Pairs = 10

    # The matchscore is expressed in Butler Imps with Avg+ as +2 and weighted datescore calculation.
    ScoringType_Imp2_Weighted = 20

    # The matchscore is expressed in Butler Imps with Avg+ as +2 and 10% omit datescore calculation.
    ScoringType_Imp2_10Percent = 21

    # The matchscore is expressed in Butler Imps with Avg+ as +2 and no correection for datescore
    # calculation.
    ScoringType_Imp2_NoCorrection = 22

    # The matchscore is expressed in Butler Imps with Avg+ as +3 and weighted datescore calculation.
    ScoringType_Imp3_Weighted = 25

    # The matchscore is expressed in Butler Imps with Avg+ as +3 and 10% omit datescore calculation.
    ScoringType_Imp3_10Percent = 26

    # The matchscore is expressed in Butler Imps with Avg+ as +2 and no correection for datescore
    # calculation.
    ScoringType_Imp3_NoCorrection = 27

    # The matchscore is expressed in Cross Imps total IMPs.The Avg+=+2 IMP.
    ScoringType_XImp2_Total = 30

    # The matchscore is expressed in Cross Imps average IMPs.The Avg+=+2 IMP.
    ScoringType_XImp2_Average = 31

    # The matchscore is expressed in Cross Imps total IMPs.The Avg+=+3 IMP.
    ScoringType_XImp3_Total = 35

    # The matchscore is expressed in Cross Imps average IMPs.The Avg+=+3 IMP.
    ScoringType_XImp3_Average = 36

    # The matchscore is expressed in Team Imps.
    ScoringType_TeamImps = 40

    # The matchscore is expressed in discrete (whole number) Victory Points.
    ScoringType_TeamVPDiscrete = 50

    # The matchscore is expressed in continuous (floating point) Victory Points.
    ScoringType_TeamVPContinuous = 51

    # The matchscore is expressed in Board-a-Match points.
    ScoringType_Bam = 60

    # The matchscore is expressed as a Patton score.
    ScoringType_Patton = 70

    # Required, must match the Guid of its SessionDTO parent.
    session_guid: str | None = None

    # Required when using http for communication with the data connector.
    club_id: str | None = None

    # Required when the dto is part of the InitDTO, must be at least one. Optional when the dto is
    # used for scoringgroup updates. Must be empty if the IsDeleted property is true.
    sections: list[SectionDTO] | None = None

    # Required, must be unique and greater than zero.
    scoring_group_number: int = 0

    # Required. Pairs = 10, IMP = 20, XIMP = 30, TeamIMP = 40, TeamsVPDiscrete = 50,
    # TeamsVPContinuous = 51, Bam = 60, Patton = 70
    scoring_method: int = 0

    # Optional
    name: str | None = None

    # If "True" the scoring group will be deleted if it has no more sections. Be sure to assign
    # other scoring groups to this scoringgroup's sections if its sections are not deleted. Will be
    # ignored when the dto is part of the InitDTO.
    is_deleted: bool = False

    # An array of messages describing problems in data integrity and invalid values.
    validation_messages: list[str] | None = None

    def to_dict(self) -> dict:
        """The JSON-ready dict with the PascalCase wire names, in wire order."""
        return {
            "SessionGuid": self.session_guid,
            "ClubId": self.club_id,
            "Sections": [item.to_dict() for item in self.sections] if self.sections is not None else None,
            "ScoringGroupNumber": self.scoring_group_number,
            "ScoringMethod": self.scoring_method,
            "Name": self.name,
            "IsDeleted": self.is_deleted,
            "ValidationMessages": self.validation_messages,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ScoringGroupDTO":
        """Builds the DTO from a parsed JSON dict; absent or null values keep the field defaults."""
        dto = cls()
        dto.session_guid = data.get("SessionGuid")
        dto.club_id = data.get("ClubId")
        dto.sections = [SectionDTO.from_dict(item) for item in data["Sections"]] if data.get("Sections") is not None else None
        dto.scoring_group_number = data["ScoringGroupNumber"] if data.get("ScoringGroupNumber") is not None else 0
        dto.scoring_method = data["ScoringMethod"] if data.get("ScoringMethod") is not None else 0
        dto.name = data.get("Name")
        dto.is_deleted = data["IsDeleted"] if data.get("IsDeleted") is not None else False
        dto.validation_messages = data.get("ValidationMessages")
        return dto
