# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class ScoringProgramDataConnectorCommands(IntEnum):
    """These enum values comprise the command values that can be set on the ScoringProgramRequest's
    Command property. Not all of these are currently supported. In the comments after the values
    the associated Data Transfer Object (DTO) is mentioned if applicable.
    """

    # Invalid, never use
    None_ = 0
    # Connect to the Data Connector
    Connect = 1
    # Not supported
    StopBCS = 2
    # Disconnects from the Data Connector
    Disconnect = 3
    # Checks if the Data Connnector responds
    Ping = 4
    # Initialize an event with at least one session, its scoringgroups, sections, tables and rounds.
    InitializeEvent = 5
    # Update the movement for a section, or delete the section.
    UpdateMovement = 6
    # Adds a session to a known event.
    AddSession = 7
    # Update the scoringmethod of the scoringgroups and/or rearrange the assignment of the sections
    # to them.
    UpdateScoringGroups = 8
    # Not supported
    PutTableGraph = 9
    # Upload board results to the Data Connector
    PutResults = 10
    # Upload player data to the Data Connector
    PutPlayerData = 11
    # Upload participations to the Data Connector
    PutParticipations = 12
    # Upload handrecords to the Data Connector
    PutHandrecords = 13
    # Upload Bridgemate 2 settings to the Data Connector
    PutBridgemate2Settings = 14
    # Upload Bridgemate 3 settings results to the Data Connector
    PutBridgemate3Settings = 15
    # Not supported
    UpdateSession = 16
    # Not supported
    UpdateSection = 17
    # Not supported
    UpdateTable = 18
    # Query the Data Connector for new board results.
    PollQueueForNewResults = 19
    # Query the Data Connector for new player data.
    PollQueueForNewPlayerData = 20
    # Query the Data Connector for new participations.
    PollQueueForNewParticipations = 21
    # Query the Data Connector for new handrecords.
    PollQueueForNewHandrecords = 22
    # Request all board results for the session from the Data Connector.
    PollQueueForAllResults = 23
    # Request all player data for the session from the Data Connector.
    PollQueueForAllPlayerData = 24
    # Request all participations results for the session from the Data Connector.
    PollQueueForAllParticipations = 25
    # Request all handrecords for the session from the Data Connector.
    PollQueueForAllHandrecords = 26
    # Accept the new board results: the Data Connector will not send them again, unless the
    # PollQueueForAllResults command is used.
    AcceptResultQueueItems = 27
    # Accept the new player data: the Data Connector will not send them again, unless the
    # PollQueueForAllPlayerData command is used.
    AcceptPlayerDataQueueItems = 28
    # Accept the new participations: the Data Connector will not send them again, unless the
    # PollQueueForAllParticipations command is used.
    AcceptParticipantQueueItems = 29
    # Accept the new handrecords: the Data Connector will not send them again, unless the
    # PollQueueForAllHandrecords command is used.
    AcceptHandrecordQueueItems = 30
    # Continue an event that was start before using the InitializeEvent command.
    ContinueEvent = 31
    # Requests the movement for a specific section from the Data Connector.
    GetMovement = 32
    # Requests all movements of a session from the Data Connector
    GetAllMovements = 33
    # Queries BCS for either the running session or all known sessions. Also used to request BCS to
    # shut down.
    ManageBCS = 34
    # Instructs the DataConnector to clear all incoming and outgoing queue data.
    ClearData = 35
    # Query the Data Connector for new td calls.
    PollQueueForNewTdCalls = 36
    # Query the Data Connector for all td calls.
    PollQueueForAllTdCalls = 37
    # Accept the new td calls: the Data Connector will not send them again, unless the
    # PollQueueForAllTdCalls command is used.
    AcceptTdCallQueueItems = 38
    # Upload td calls to the Data Connector
    PutTdCalls = 39
    # Not supported
    TestData = 40

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.None_
