# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from dataclasses import dataclass

from ._support import enum_from_wire
from .data_connector_response_data import DataConnectorResponseData
from .error_type import ErrorType
from .scoring_program_data_connector_commands import ScoringProgramDataConnectorCommands


@dataclass
class ScoringProgramResponse:
    """This class carries the response data that the Data Connector sends back after sending it a
    ScoringProgramRequest.
    """

    # The command of the request that this is the reponse for.
    request_command: ScoringProgramDataConnectorCommands = ScoringProgramDataConnectorCommands.None_

    # Specifies the datatype to deserialize to after reception of the response.
    # DataConnectorResponseData.Error signals that something went wrong. The serialized data in that
    # case will be a string describing the error.
    data_type: DataConnectorResponseData = DataConnectorResponseData.None_

    # If the response contains queue data the id of last added queueitem.
    last_queue_item_id: int = 0

    # Specifies the type of error that occurred. ErrorType.None if all went well.
    error_type: ErrorType = ErrorType.None_

    # The guid of the session the response belongs to.
    session_guid: str | None = None

    # The serialized data. The DataType property tells to what class it should be deserialized.
    serialized_data: str | None = None

    def to_dict(self) -> dict:
        """The JSON-ready dict with the PascalCase wire names, in wire order."""
        return {
            "RequestCommand": int(self.request_command),
            "DataType": int(self.data_type),
            "LastQueueItemId": self.last_queue_item_id,
            "ErrorType": int(self.error_type),
            "SessionGuid": self.session_guid,
            "SerializedData": self.serialized_data,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ScoringProgramResponse":
        """Builds the DTO from a parsed JSON dict; absent or null values keep the field defaults."""
        dto = cls()
        dto.request_command = enum_from_wire(ScoringProgramDataConnectorCommands, data.get("RequestCommand"), ScoringProgramDataConnectorCommands.None_)
        dto.data_type = enum_from_wire(DataConnectorResponseData, data.get("DataType"), DataConnectorResponseData.None_)
        dto.last_queue_item_id = data["LastQueueItemId"] if data.get("LastQueueItemId") is not None else 0
        dto.error_type = enum_from_wire(ErrorType, data.get("ErrorType"), ErrorType.None_)
        dto.session_guid = data.get("SessionGuid")
        dto.serialized_data = data.get("SerializedData")
        return dto
