# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from dataclasses import dataclass

from ._support import enum_from_wire
from .scoring_program_data_connector_commands import ScoringProgramDataConnectorCommands


@dataclass
class ScoringProgramRequest:
    """This class carries both a command and its associated data (if any) for the Data Connector.
    If the command pertains to a specific session the SessionGuid property has to be set.
    Validation will check in that case if the SessionGuid properties of the SerializedData has
    the same value. The Data Connector always responds with a ScoringProgramResponse
    """

    # Required. The command that the Data Connector must pass on to BCS.
    command: ScoringProgramDataConnectorCommands = ScoringProgramDataConnectorCommands.None_

    # Required when using the http interface for the dataconnector
    club_id: str | None = None

    # Required when using the http interface for the dataconnector
    licence_key: str | None = None

    # Required if the command pertains to a session. Must be empty otherwise.
    session_guid: str | None = None

    # The data associated with the command, if any. Must be serialized as JSON.
    serialized_data: str | None = None

    def to_dict(self) -> dict:
        """The JSON-ready dict with the PascalCase wire names, in wire order."""
        return {
            "Command": int(self.command),
            "ClubId": self.club_id,
            "LicenceKey": self.licence_key,
            "SessionGuid": self.session_guid,
            "SerializedData": self.serialized_data,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ScoringProgramRequest":
        """Builds the DTO from a parsed JSON dict; absent or null values keep the field defaults."""
        dto = cls()
        dto.command = enum_from_wire(ScoringProgramDataConnectorCommands, data.get("Command"), ScoringProgramDataConnectorCommands.None_)
        dto.club_id = data.get("ClubId")
        dto.licence_key = data.get("LicenceKey")
        dto.session_guid = data.get("SessionGuid")
        dto.serialized_data = data.get("SerializedData")
        return dto
