# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from dataclasses import dataclass

from .participation_dto import ParticipationDTO
from .player_data_dto import PlayerDataDTO
from .table_dto import TableDTO


@dataclass
class SectionUpdateDTO:
    """Contains information for an updated or added section"""

    # Required. The guid of the session the section is part of. A string built from a Guid, without
    # the curly braces or connecting dashes. The letters must be capitals
    session_guid: str | None = None

    # Required when using the http interface for the dataconnector
    club_id: str | None = None

    # Required, the number of the scoringgroup the section belongs to. Must be greater than zero. If
    # the scoringgroup already exists the section wull be added to it, otherwise a new scoringgroup
    # wil be added.
    scoring_group_number: int = 0

    # Must be set and must match the scoringmethod of the scoringgroup if the section is added to
    # one, otherwise it will specify the scoringmethod for the new scoringgroup. See for valid
    # values the ScoringType contstants in the ScoringGroupDTO.
    scoring_group_scoring_method: int = 0

    # Required. The letters of the section. If a section with this letters already exists it will be
    # updated. Otherwise the section will be added. Can be A-Z, AA, BB, CC,...ZZ, AAA, BBB, CCC, ...
    # ZZZ
    letters: str | None = None

    # Optional.
    name: str | None = None

    # Required: either 1 or 2.
    winners: int = 0

    game_type: int = 0

    # Negative value: the eastwest pairs move down the specified number of tables before play
    # starts. Positive value: the eastwest pairs move up the specified number of tables before play
    # starts. Zero: the eastwest pairs do not move. Currently not supported.
    ew_move_before_play: int = 0

    # Optional. A pair that is missing throughout the movement. Alternatively this can be specified
    # by Leaving out the opponent for a pair that would have met the missing pair. However, BCS will
    # be able to discern a sit-out table from an empty table if this value is used. When using a two
    # winner movement a positive number denotes a missing NS pair, a negative value denotes a
    # missing EW pair.
    missing_pair: int = 0

    # When "true" the Bridgemate (2) server will be instructed to net close the session when the
    # result for the last available round have been received. In this way it is possible to play
    # Swiss matches.
    keep_bridgemates_alive: bool = False

    # If true the SitoutSectionLetters must have the value for an existing section.
    is_combi_section: bool = False

    # Required if IsCombiSection is True. Must be the letters for an existing section. The letters
    # of the section the North-South pairs in the combisection originate from.
    north_south_pair_section_letters: str | None = None

    # Required if IsCombisection is True. Must be the letters for an existing section. The letters
    # of the section the East-West pairs in the combisection originate from.
    east_west_pair_section_letters: str | None = None

    # Marks the section for deletion. No tables must be specified. ALl properties other than the
    # SessionGuid an Letters are ignored.
    is_deleted: bool = False

    # Optional. Any players that have been added and were not included while initializing the
    # session.
    added_players: list[PlayerDataDTO] | None = None

    # Optional. The players as they are seated in the first round. Be sure to include players as
    # well that do not play in the first round.
    participations: list[ParticipationDTO] | None = None

    # An array of TableDTOs. All tables for the section must be specified. If the section is to be
    # deleted, no tables must be specified.
    tables: list[TableDTO] | None = None

    # An array of messages describing problems in data integrity and invalid values.
    validation_messages: list[str] | None = None

    def to_dict(self) -> dict:
        """The JSON-ready dict with the PascalCase wire names, in wire order."""
        return {
            "SessionGuid": self.session_guid,
            "ClubId": self.club_id,
            "ScoringGroupNumber": self.scoring_group_number,
            "ScoringGroupScoringMethod": self.scoring_group_scoring_method,
            "Letters": self.letters,
            "Name": self.name,
            "Winners": self.winners,
            "GameType": self.game_type,
            "EWMoveBeforePlay": self.ew_move_before_play,
            "MissingPair": self.missing_pair,
            "KeepBridgematesAlive": self.keep_bridgemates_alive,
            "IsCombiSection": self.is_combi_section,
            "NorthSouthPairSectionLetters": self.north_south_pair_section_letters,
            "EastWestPairSectionLetters": self.east_west_pair_section_letters,
            "IsDeleted": self.is_deleted,
            "AddedPlayers": [item.to_dict() for item in self.added_players] if self.added_players is not None else None,
            "Participations": [item.to_dict() for item in self.participations] if self.participations is not None else None,
            "Tables": [item.to_dict() for item in self.tables] if self.tables is not None else None,
            "ValidationMessages": self.validation_messages,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "SectionUpdateDTO":
        """Builds the DTO from a parsed JSON dict; absent or null values keep the field defaults."""
        dto = cls()
        dto.session_guid = data.get("SessionGuid")
        dto.club_id = data.get("ClubId")
        dto.scoring_group_number = data["ScoringGroupNumber"] if data.get("ScoringGroupNumber") is not None else 0
        dto.scoring_group_scoring_method = data["ScoringGroupScoringMethod"] if data.get("ScoringGroupScoringMethod") is not None else 0
        dto.letters = data.get("Letters")
        dto.name = data.get("Name")
        dto.winners = data["Winners"] if data.get("Winners") is not None else 0
        dto.game_type = data["GameType"] if data.get("GameType") is not None else 0
        dto.ew_move_before_play = data["EWMoveBeforePlay"] if data.get("EWMoveBeforePlay") is not None else 0
        dto.missing_pair = data["MissingPair"] if data.get("MissingPair") is not None else 0
        dto.keep_bridgemates_alive = data["KeepBridgematesAlive"] if data.get("KeepBridgematesAlive") is not None else False
        dto.is_combi_section = data["IsCombiSection"] if data.get("IsCombiSection") is not None else False
        dto.north_south_pair_section_letters = data.get("NorthSouthPairSectionLetters")
        dto.east_west_pair_section_letters = data.get("EastWestPairSectionLetters")
        dto.is_deleted = data["IsDeleted"] if data.get("IsDeleted") is not None else False
        dto.added_players = [PlayerDataDTO.from_dict(item) for item in data["AddedPlayers"]] if data.get("AddedPlayers") is not None else None
        dto.participations = [ParticipationDTO.from_dict(item) for item in data["Participations"]] if data.get("Participations") is not None else None
        dto.tables = [TableDTO.from_dict(item) for item in data["Tables"]] if data.get("Tables") is not None else None
        dto.validation_messages = data.get("ValidationMessages")
        return dto
