# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from dataclasses import dataclass

from .scoring_group_dto import ScoringGroupDTO


@dataclass
class SessionDTO:
    """A group of sections that are usually played at the same time and place. Pairs will subscribe
    to participate in a specific session. If BCS has to administer more than one session at the
    same time, these sessions must share a comment EventGuid property.
    """

    # Required, must be at least one.
    scoring_groups: list[ScoringGroupDTO] | None = None

    # Optional. A string built from a Guid, without the curly braces or connecting dashes. The
    # letters must be capitals Must be unique if used.
    event_guid: str | None = None

    # Required.A string built from a Guid, without the curly braces or connecting dashes. The
    # letters must be capitals Must be unique
    session_guid: str | None = None

    # Required. The name of the session.
    name: str | None = None

    # Required. The year in which the session is played.
    year: int = 0

    # Required. The month in which the session is played.
    month: int = 0

    # Required. The day on which the session is played.
    day: int = 0

    # Optional. The starting hour for the session.
    hour: int = 0

    # Optional. The starting minutes for the session.
    minute: int = 0

    # If True will show the session in the Bridgemate App, if the Bridgemae App has been configured
    # in BCS.
    show_in_app: bool = False

    ew_return_home: bool = False

    pairs_move_accross_field: bool = False

    # An array of messages describing problems in data integrity and invalid values.
    validation_messages: list[str] | None = None

    def to_dict(self) -> dict:
        """The JSON-ready dict with the PascalCase wire names, in wire order."""
        return {
            "ScoringGroups": [item.to_dict() for item in self.scoring_groups] if self.scoring_groups is not None else None,
            "EventGuid": self.event_guid,
            "SessionGuid": self.session_guid,
            "Name": self.name,
            "Year": self.year,
            "Month": self.month,
            "Day": self.day,
            "Hour": self.hour,
            "Minute": self.minute,
            "ShowInApp": self.show_in_app,
            "EWReturnHome": self.ew_return_home,
            "PairsMoveAccrossField": self.pairs_move_accross_field,
            "ValidationMessages": self.validation_messages,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "SessionDTO":
        """Builds the DTO from a parsed JSON dict; absent or null values keep the field defaults."""
        dto = cls()
        dto.scoring_groups = [ScoringGroupDTO.from_dict(item) for item in data["ScoringGroups"]] if data.get("ScoringGroups") is not None else None
        dto.event_guid = data.get("EventGuid")
        dto.session_guid = data.get("SessionGuid")
        dto.name = data.get("Name")
        dto.year = data["Year"] if data.get("Year") is not None else 0
        dto.month = data["Month"] if data.get("Month") is not None else 0
        dto.day = data["Day"] if data.get("Day") is not None else 0
        dto.hour = data["Hour"] if data.get("Hour") is not None else 0
        dto.minute = data["Minute"] if data.get("Minute") is not None else 0
        dto.show_in_app = data["ShowInApp"] if data.get("ShowInApp") is not None else False
        dto.ew_return_home = data["EWReturnHome"] if data.get("EWReturnHome") is not None else False
        dto.pairs_move_accross_field = data["PairsMoveAccrossField"] if data.get("PairsMoveAccrossField") is not None else False
        dto.validation_messages = data.get("ValidationMessages")
        return dto
