# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from enum import IntEnum


class TableDirection(IntEnum):
    """Specifies the positions on a table."""

    # No position specified.
    None_ = 0
    # North
    North = 1
    # East
    East = 2
    # South
    South = 3
    # West
    West = 4

    @classmethod
    def _missing_(cls, value):
        # Unknown wire values (from a newer Data Connector) map to the zero case
        # instead of failing the whole response.
        return cls.None_
