# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from dataclasses import dataclass

from ._support import enum_from_wire
from .bm3_connection_mode_option import Bm3ConnectionModeOption
from .round_dto import RoundDTO


@dataclass
class TableDTO:
    """A class describing a real or virtual bridge table where each round two pairs will compete."""

    # Required. The guid of the session the table belongs to.
    session_guid: str | None = None

    # Required, the letters of the section the table belongs to. The section must exist.
    section_letters: str | None = None

    # Required, must be greater than zero and must be unique within the section.
    table_number: int = 0

    # Optional: specifies if the Bridgemate on the table should work in online mode (default) or
    # offline mode. In offline mode the Bridgemate will not communicate with the Bridgemate 3 server
    # during the session, but will try to send its results after the last board had been played.
    # Because of this the Bridgemate will not respond to movement updates. Mind: this setting will
    # only have effect when the Bridgemate first connects to the session. Once a Bridgemate has been
    # initialized with movement data the ConnectionMode cannot be changed until the Bridgemate is
    # restarted.
    connection_mode: Bm3ConnectionModeOption = Bm3ConnectionModeOption.Online

    # If set to "True" the Bridgemates will await new rounddata after all results have been entered
    # for the existing rounds on the tables. Otherwise, by default, the Bridgemate will signal end
    # of session when all the results its expects have been entered.
    keep_bridgemates_alive: bool = False

    # Required. An array of RoundDTOs describing which pairs will meet on this table and which
    # boards they will play.
    rounds: list[RoundDTO] | None = None

    # An array of messages describing problems in data integrity and invalid values.
    validation_messages: list[str] | None = None

    def to_dict(self) -> dict:
        """The JSON-ready dict with the PascalCase wire names, in wire order."""
        return {
            "SessionGuid": self.session_guid,
            "SectionLetters": self.section_letters,
            "TableNumber": self.table_number,
            "ConnectionMode": int(self.connection_mode),
            "KeepBridgematesAlive": self.keep_bridgemates_alive,
            "Rounds": [item.to_dict() for item in self.rounds] if self.rounds is not None else None,
            "ValidationMessages": self.validation_messages,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "TableDTO":
        """Builds the DTO from a parsed JSON dict; absent or null values keep the field defaults."""
        dto = cls()
        dto.session_guid = data.get("SessionGuid")
        dto.section_letters = data.get("SectionLetters")
        dto.table_number = data["TableNumber"] if data.get("TableNumber") is not None else 0
        dto.connection_mode = enum_from_wire(Bm3ConnectionModeOption, data.get("ConnectionMode"), Bm3ConnectionModeOption.Online)
        dto.keep_bridgemates_alive = data["KeepBridgematesAlive"] if data.get("KeepBridgematesAlive") is not None else False
        dto.rounds = [RoundDTO.from_dict(item) for item in data["Rounds"]] if data.get("Rounds") is not None else None
        dto.validation_messages = data.get("ValidationMessages")
        return dto
