# Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
from dataclasses import dataclass



@dataclass
class TdCallDTO:
    """Contains information about a TD call."""

    # The TD call status has been iniiated.
    TdCallStatus_Launched = 1

    # The TD is at the table.
    TdCallStatus_InProgress = 2

    # The call has been resolved.
    TdCallStatus_Resolved = 3

    # Resolution of the call has been deferred.
    TdCallStatus_Deferred = 4

    # Required. The guid of the session the td call belongs to.
    session_guid: str | None = None

    # Required, the letters of the section the td call belongs to. The section must exist.
    section_letters: str | None = None

    # Required, the table in the section where the td call originates from.
    table_number: int = 0

    # Required. The round om the table where the td call is generated from.
    round_number: int = 0

    # The hour at which the td call was generated. Use 24 hours to a day.
    hour: int = 0

    # The minute in which the td call was generated.
    minute: int = 0

    # Required. Valid values are: 1: Launched 2: InProgress 3. Resolved 4: Deferred
    status: int = 0

    # An array of messages describing problems in data integrity and invalid values.
    validation_messages: list[str] | None = None

    def to_dict(self) -> dict:
        """The JSON-ready dict with the PascalCase wire names, in wire order."""
        return {
            "SessionGuid": self.session_guid,
            "SectionLetters": self.section_letters,
            "TableNumber": self.table_number,
            "RoundNumber": self.round_number,
            "Hour": self.hour,
            "Minute": self.minute,
            "Status": self.status,
            "ValidationMessages": self.validation_messages,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "TdCallDTO":
        """Builds the DTO from a parsed JSON dict; absent or null values keep the field defaults."""
        dto = cls()
        dto.session_guid = data.get("SessionGuid")
        dto.section_letters = data.get("SectionLetters")
        dto.table_number = data["TableNumber"] if data.get("TableNumber") is not None else 0
        dto.round_number = data["RoundNumber"] if data.get("RoundNumber") is not None else 0
        dto.hour = data["Hour"] if data.get("Hour") is not None else 0
        dto.minute = data["Minute"] if data.get("Minute") is not None else 0
        dto.status = data["Status"] if data.get("Status") is not None else 0
        dto.validation_messages = data.get("ValidationMessages")
        return dto
